import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { FeaturesSection } from "@/components/features-section"
import { TestimonialsSection } from "@/components/testimonials-section"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { ArrowRight, Sparkles, Zap, Shield, BarChart3, Users, Clock } from "lucide-react"

export const metadata = {
  title: "Features | MathBeast",
  description: "Discover the powerful features that make MathBeast the leading AI-powered math learning platform.",
}

const highlights = [
  {
    icon: Sparkles,
    title: "AI-Powered Solutions",
    description: "Get step-by-step explanations generated by GPT-OSS-120B with chain-of-thought reasoning.",
  },
  {
    icon: Zap,
    title: "Instant Feedback",
    description: "Receive real-time hints and corrections as you work through problems.",
  },
  {
    icon: Shield,
    title: "Adaptive Difficulty",
    description: "Problems automatically adjust to your skill level for optimal learning.",
  },
  {
    icon: BarChart3,
    title: "Progress Tracking",
    description: "Visualize your improvement with detailed analytics and knowledge maps.",
  },
  {
    icon: Users,
    title: "Competition Ready",
    description: "Prepare for math olympiads and competitions with curated problem sets.",
  },
  {
    icon: Clock,
    title: "24/7 Availability",
    description: "Learn anytime, anywhere with always-available AI tutoring.",
  },
]

export default function FeaturesPage() {
  return (
    <main className="min-h-screen">
      <Header />

      {/* Hero Banner */}
      <section className="pt-28 pb-16 bg-gradient-to-br from-primary/10 via-background to-secondary/10">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <div className="inline-flex items-center gap-2 bg-primary/10 text-primary px-4 py-2 rounded-full text-sm font-medium mb-6">
              <Sparkles className="h-4 w-4" />
              Platform Features
            </div>
            <h1 className="text-4xl md:text-5xl font-extrabold text-foreground mb-6 text-balance">
              Everything You Need to Master Math
            </h1>
            <p className="text-lg text-muted-foreground leading-relaxed">
              MathBeast combines cutting-edge AI with proven pedagogical methods to create the most effective math
              learning experience available.
            </p>
          </div>

          {/* Highlights Grid */}
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
            {highlights.map((item) => (
              <div
                key={item.title}
                className="bg-card rounded-2xl p-6 border border-border hover:border-primary/50 hover:shadow-lg transition-all group"
              >
                <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center mb-4 group-hover:bg-primary/20 transition-colors">
                  <item.icon className="h-6 w-6 text-primary" />
                </div>
                <h3 className="text-lg font-bold text-foreground mb-2">{item.title}</h3>
                <p className="text-muted-foreground">{item.description}</p>
              </div>
            ))}
          </div>

          <div className="text-center">
            <Link href="/demo">
              <Button size="lg" className="rounded-full gap-2 bg-gradient-to-r from-primary to-secondary">
                Try It Now
                <ArrowRight className="h-5 w-5" />
              </Button>
            </Link>
          </div>
        </div>
      </section>

      <FeaturesSection />
      <TestimonialsSection />

      {/* CTA Section */}
      <section className="py-20 bg-muted">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-6">Start Your Learning Journey Today</h2>
          <p className="text-lg text-muted-foreground mb-8">
            Join over 10,000 students who have improved their math skills with MathBeast.
          </p>
          <div className="flex flex-wrap justify-center gap-4">
            <Link href="/dashboard">
              <Button size="lg" className="rounded-full gap-2 bg-gradient-to-r from-primary to-secondary">
                Get Started Free
                <ArrowRight className="h-5 w-5" />
              </Button>
            </Link>
            <Link href="/api-docs">
              <Button size="lg" variant="outline" className="rounded-full bg-transparent">
                View API Docs
              </Button>
            </Link>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  )
}
